[package]
name = "client_chat"
version = "0.1.0"
authors = ["Rasmus Dahlkvist <elfanos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.18.0"
crossterm = "0.24.0"
unicode-width = "0.1"
